// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataVolumeItem) DeepCopyInto(out *DataVolumeItem) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataVolumeItem.
func (in *DataVolumeItem) DeepCopy() *DataVolumeItem {
	if in == nil {
		return nil
	}
	out := new(DataVolumeItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderCredentialsSecret) DeepCopyInto(out *ProviderCredentialsSecret) {
	*out = *in
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderCredentialsSecret.
func (in *ProviderCredentialsSecret) DeepCopy() *ProviderCredentialsSecret {
	if in == nil {
		return nil
	}
	out := new(ProviderCredentialsSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceMappingsSpec) DeepCopyInto(out *ResourceMappingsSpec) {
	*out = *in
	if in.ConfigMapNamespace != nil {
		in, out := &in.ConfigMapNamespace, &out.ConfigMapNamespace
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceMappingsSpec.
func (in *ResourceMappingsSpec) DeepCopy() *ResourceMappingsSpec {
	if in == nil {
		return nil
	}
	out := new(ResourceMappingsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineImport) DeepCopyInto(out *VirtualMachineImport) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineImport.
func (in *VirtualMachineImport) DeepCopy() *VirtualMachineImport {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineImport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineImport) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineImportCondition) DeepCopyInto(out *VirtualMachineImportCondition) {
	*out = *in
	if in.Reason != nil {
		in, out := &in.Reason, &out.Reason
		*out = new(string)
		**out = **in
	}
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
	if in.LastHeartbeatTime != nil {
		in, out := &in.LastHeartbeatTime, &out.LastHeartbeatTime
		*out = (*in).DeepCopy()
	}
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineImportCondition.
func (in *VirtualMachineImportCondition) DeepCopy() *VirtualMachineImportCondition {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineImportCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineImportList) DeepCopyInto(out *VirtualMachineImportList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VirtualMachineImport, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineImportList.
func (in *VirtualMachineImportList) DeepCopy() *VirtualMachineImportList {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineImportList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineImportList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineImportOvirtSourceSpec) DeepCopyInto(out *VirtualMachineImportOvirtSourceSpec) {
	*out = *in
	in.VM.DeepCopyInto(&out.VM)
	in.ProviderCredentialsSecret.DeepCopyInto(&out.ProviderCredentialsSecret)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineImportOvirtSourceSpec.
func (in *VirtualMachineImportOvirtSourceSpec) DeepCopy() *VirtualMachineImportOvirtSourceSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineImportOvirtSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineImportOvirtSourceVMClusterSpec) DeepCopyInto(out *VirtualMachineImportOvirtSourceVMClusterSpec) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineImportOvirtSourceVMClusterSpec.
func (in *VirtualMachineImportOvirtSourceVMClusterSpec) DeepCopy() *VirtualMachineImportOvirtSourceVMClusterSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineImportOvirtSourceVMClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineImportOvirtSourceVMSpec) DeepCopyInto(out *VirtualMachineImportOvirtSourceVMSpec) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Cluster != nil {
		in, out := &in.Cluster, &out.Cluster
		*out = new(VirtualMachineImportOvirtSourceVMClusterSpec)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineImportOvirtSourceVMSpec.
func (in *VirtualMachineImportOvirtSourceVMSpec) DeepCopy() *VirtualMachineImportOvirtSourceVMSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineImportOvirtSourceVMSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineImportSourceSpec) DeepCopyInto(out *VirtualMachineImportSourceSpec) {
	*out = *in
	if in.Ovirt != nil {
		in, out := &in.Ovirt, &out.Ovirt
		*out = new(VirtualMachineImportOvirtSourceSpec)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineImportSourceSpec.
func (in *VirtualMachineImportSourceSpec) DeepCopy() *VirtualMachineImportSourceSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineImportSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineImportSpec) DeepCopyInto(out *VirtualMachineImportSpec) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
	in.ResourceMappings.DeepCopyInto(&out.ResourceMappings)
	if in.TargetVirtualMachineName != nil {
		in, out := &in.TargetVirtualMachineName, &out.TargetVirtualMachineName
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineImportSpec.
func (in *VirtualMachineImportSpec) DeepCopy() *VirtualMachineImportSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineImportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineImportStatus) DeepCopyInto(out *VirtualMachineImportStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]VirtualMachineImportCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DataVolumes != nil {
		in, out := &in.DataVolumes, &out.DataVolumes
		*out = make([]DataVolumeItem, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineImportStatus.
func (in *VirtualMachineImportStatus) DeepCopy() *VirtualMachineImportStatus {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineImportStatus)
	in.DeepCopyInto(out)
	return out
}
