// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha3

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineImport) DeepCopyInto(out *VirtualMachineImport) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineImport.
func (in *VirtualMachineImport) DeepCopy() *VirtualMachineImport {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineImport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineImport) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineImportList) DeepCopyInto(out *VirtualMachineImportList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VirtualMachineImport, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineImportList.
func (in *VirtualMachineImportList) DeepCopy() *VirtualMachineImportList {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineImportList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineImportList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineImportOvirtSourceSpec) DeepCopyInto(out *VirtualMachineImportOvirtSourceSpec) {
	*out = *in
	out.VM = in.VM
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineImportOvirtSourceSpec.
func (in *VirtualMachineImportOvirtSourceSpec) DeepCopy() *VirtualMachineImportOvirtSourceSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineImportOvirtSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineImportOvirtSourceVMSpec) DeepCopyInto(out *VirtualMachineImportOvirtSourceVMSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineImportOvirtSourceVMSpec.
func (in *VirtualMachineImportOvirtSourceVMSpec) DeepCopy() *VirtualMachineImportOvirtSourceVMSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineImportOvirtSourceVMSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineImportSourceSpec) DeepCopyInto(out *VirtualMachineImportSourceSpec) {
	*out = *in
	out.Ovirt = in.Ovirt
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineImportSourceSpec.
func (in *VirtualMachineImportSourceSpec) DeepCopy() *VirtualMachineImportSourceSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineImportSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineImportSpec) DeepCopyInto(out *VirtualMachineImportSpec) {
	*out = *in
	out.Source = in.Source
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineImportSpec.
func (in *VirtualMachineImportSpec) DeepCopy() *VirtualMachineImportSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineImportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineImportStatus) DeepCopyInto(out *VirtualMachineImportStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineImportStatus.
func (in *VirtualMachineImportStatus) DeepCopy() *VirtualMachineImportStatus {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineImportStatus)
	in.DeepCopyInto(out)
	return out
}
